
USE GameStore;
INSERT INTO JUEGOS VALUES ('HOLLOW KNIGHT', 'AVENTURA' );
INSERT INTO JUEGOS VALUES ('AMNESIA', 'TERROR Y SUSPENSO' );
INSERT INTO JUEGOS VALUES ('MONSTER HUNTER', 'WORLD ROL' );
INSERT INTO JUEGOS VALUES ('FALLOUT', 'ACCION ' );
INSERT INTO JUEGOS VALUES ('OUTLAST', 'TERROR' );
SELECT* FROM JUEGOS
